Repository cytomine/cytomine-app-store, pull requests merged in 2025-08, with the labels that each got.

#12 feat: add java backend
  .gitignore
  backend/Dockerfile
  backend/HELP.md
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/be/cytomine/appstore/AppstoreApplication.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/master-changelog.yml
  backend/src/test/java/be/cytomine/appstore/AppstoreApplicationTests.java
  docker-compose.yml
Labels: enhancement

#11 feat: add frontend boilerplate
  .gitattributes
  frontend/.gitignore
  frontend/Dockerfile
  frontend/README.md
  frontend/env.d.ts
  frontend/eslint.config.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/components/navbar/AppNavbar.vue
  frontend/src/i18n.ts
  frontend/src/locales/json/en.i18n.json
  frontend/src/locales/json/fr.i18n.json
  frontend/src/locales/translations.csv
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/stores/counter.ts
  frontend/src/types/vue-i18n.d.ts
  frontend/src/types/vue-shims.d.ts
  frontend/tests/e2e/vue.test.ts
  frontend/tests/unit/App.spec.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/tsconfig.vitest.json
  frontend/vite.config.ts
  frontend/vitest.config.ts
Labels: enhancement

#28 ci: fix backend tests
  .github/workflows/ci.yaml
Labels: ci/cd

#23 ci: add frontend lint and test
  .github/workflows/ci.yaml
Labels: ci/cd

#27 feat: add the download of a task bundle api
  backend/build.gradle
  backend/src/main/java/be/cytomine/appstore/controllers/TaskController.java
  backend/src/main/java/be/cytomine/appstore/dto/responses/errors/details/MultipleErrors.java
  backend/src/main/java/be/cytomine/appstore/handlers/RegistryHandler.java
  backend/src/main/java/be/cytomine/appstore/handlers/StorageData.java
  backend/src/main/java/be/cytomine/appstore/handlers/registry/impl/DockerRegistryHandler.java
  backend/src/main/java/be/cytomine/appstore/services/TaskService.java
  backend/src/test/java/be/cytomine/appstore/services/TaskServiceTest.java
  backend/src/test/java/be/cytomine/appstore/utils/ApiClient.java
Labels: enhancement

#26 feat: add simple tasks page search api
  backend/settings.gradle
  backend/src/main/java/be/cytomine/appstore/controllers/TaskController.java
  backend/src/main/java/be/cytomine/appstore/dto/responses/errors/ErrorCode.java
  backend/src/main/java/be/cytomine/appstore/models/Search.java
  backend/src/main/java/be/cytomine/appstore/models/task/Type.java
  backend/src/main/java/be/cytomine/appstore/repositories/SearchRepository.java
  backend/src/main/java/be/cytomine/appstore/repositories/TaskRepository.java
  backend/src/main/java/be/cytomine/appstore/services/TaskService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/master-changelog.yml
  backend/src/main/resources/migrations/init.postgresql.sql
  backend/src/main/resources/migrations/materialized_view.sql
  backend/src/test/java/be/cytomine/appstore/AppstoreApplicationTests.java
  backend/src/test/java/be/cytomine/appstore/config/TestConfig.java
  backend/src/test/java/be/cytomine/appstore/handlers/StorageTest.java
  backend/src/test/java/be/cytomine/appstore/repositories/SearchRepositoryTest.java
  backend/src/test/java/be/cytomine/appstore/services/TaskServiceTest.java
  backend/src/test/java/be/cytomine/appstore/services/TaskValidationServiceTest.java
  backend/src/test/java/be/cytomine/appstore/utils/ApiClient.java
  backend/src/test/java/be/cytomine/appstore/utils/ArchiveUtilsTest.java
  backend/src/test/java/be/cytomine/appstore/utils/TaskUtils.java
  backend/src/test/java/be/cytomine/appstore/utils/TestTaskBuilder.java
  backend/src/test/java/be/cytomine/appstore/utils/UnitTest.java
Labels: enhancement

#40 feat: add app store page
  frontend/src/api/tasks.ts
  frontend/src/components/navbar/AppNavbar.vue
  frontend/src/locales/json/en.i18n.json
  frontend/src/locales/json/fr.i18n.json
  frontend/src/locales/translations.csv
  frontend/src/pages/AppStore.vue
  frontend/src/pages/GlobalDashboard.vue
  frontend/src/router/index.ts
  frontend/src/types/types.ts
  frontend/tests/e2e/AppStore.test.ts
  frontend/tests/unit/pages/AppStore.test.ts
  frontend/tests/unit/pages/GlobalDashboard.test.ts
Labels: enhancement

#47 feat: add my apps search
  frontend/src/composables/useTask.ts
  frontend/src/pages/AppStore.vue
  frontend/src/pages/MyAppsPage.vue
  frontend/tests/unit/composables/useTask.test.ts
  frontend/tests/unit/pages/AppStore.test.ts
Labels: enhancement

#52 style: add css file for customization
  frontend/package-lock.json
  frontend/src/App.vue
  frontend/src/assets/styles/base.css
  frontend/src/assets/styles/main.css
  frontend/src/main.ts
Labels: chore

#56 chore: bump vue related deps
  frontend/package-lock.json
  frontend/package.json
Labels: chore

#58 ci: build docker images when CI succeed
  .github/workflows/docker.yaml
  backend/Dockerfile
  frontend/Dockerfile
Labels: ci/cd

#60 fix: Update TaskService to include namespace and version in tar entry…
  backend/src/main/java/be/cytomine/appstore/services/TaskService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/be/cytomine/appstore/services/TaskServiceTest.java
  backend/src/test/resources/artifacts/logo.png
  docker-compose.dev.yaml
Labels: bug
